version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/mongoexpress
          dockerfile: Dockerfile
          context: .
 
  deploy-to-kubernetes-cluster:
    steps:
      - checkout
      - commands:
           -  kubectl apply -f mongo.yaml
           -   kubectl apply -f service.yaml
